/*
 * This source file was generated by the Gradle 'init' task
 */
//package org.example;
// Example program, commenting it out for now unless I absolutely need it
//
//public class App {
//    public String getGreeting() {
//        return "Hello World!";
//    }
//
//    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//    }
//}
