/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

/**
 * Satisfying linting standards temporarily
 */

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
