/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

/*
Creating a Javadoc comment for linting
@return bool

 */
public final class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
