---
name: Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          VALIDATE_JAVA: true
          VALIDATE_KOTLIN: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_BASH: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Run Checkstyle Linter
        uses: dbelyaev/action-checkstyle@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: "config/checkstyle/checkstyle.xml"

